### ISSUE TITLE
make_blogs_page.py is not working with the current CSV export of google sheets

### ISSUE THREAD

**Issue by Lorenzocnv** [nexacenter/rivoluzdigitale#117]
The solution is to simply add a column at the beginning of the exported Google sheet, or else fixing the index inside the code

**Comment by bassosimone** [comment]
I'd go for fixing the index inside the code. If you write a diff for that, I'll happily review it.

**Comment by Lorenzocnv** [comment]
I've just updated the index, it should work now. I've already commited the edit, the diff is available here:
https://github.com/nexacenter/rivoluzdigitale/commit/2fd738a62e5b8d690e5c33489b02c005a11aff3b#diff-e746a4c317b9628bf315df4f0d9b6b2d

**Comment by bassosimone** [comment]
Okay, for the records, it looks good to me! Thank you! 👍
